Repository caraml-dev/merlin, pull requests merged in 2024-04, with the labels that each got.

#562 add support for observability for xgboost standard model
  api/api/validator.go
  api/api/version_endpoints_api_test.go
Labels: enhancement

#560 chore(api): Fix client endpoint examples after OpenAPI3 migration
  api/client/examples/model-endpoints/main.go
  api/client/examples/project-endpoints/main.go
Labels: maintenance

#563 fix: add Merlin project as config to observation publisher
  api/pkg/observability/deployment/config.go
  api/pkg/observability/deployment/deployment.go
  api/pkg/observability/deployment/deployment_test.go
  python/observation-publisher/conf/environment/example-override.yaml
  python/observation-publisher/publisher/__main__.py
  python/observation-publisher/publisher/config.py
  python/observation-publisher/publisher/observation_sink.py
  python/observation-publisher/publisher/prediction_log_parser.py
  python/observation-publisher/tests/test_config.py
  python/observation-publisher/tests/test_observation_sink.py
  python/observation-publisher/tests/test_prediction_log_consumer.py
Labels: bug

#564 feat: handle scenarios where there is no row id but only a single prediction row
  api/pkg/inference-logger/logger/mlobs_sink.go
  api/pkg/inference-logger/logger/mlobs_sink_test.go
Labels: enhancement

#566 fix(ui): Fix unmovable replica count in TransformerStep
  ui/src/pages/version/components/forms/steps/TransformerStep.js
Labels: bug

#568 bug: Add missing request timestamp for mlobs logger
  api/pkg/inference-logger/logger/mlobs_sink.go
Labels: bug

#551 chore(api): Update go dependencies in merlin api server
  .github/workflows/merlin.yml
  Dockerfile
  Makefile
  api/batch/controller.go
  api/batch/controller_test.go
  api/cluster/controller.go
  api/cluster/resource/templater.go
  api/cmd/api/setup.go
  api/cmd/inference-logger/main.go
  api/cmd/transformer/main.go
  api/go.mod
  api/go.sum
  api/models/model_endpoint_alert.go
  api/models/model_endpoint_alert_test.go
  api/pkg/imagebuilder/imagebuilder.go
  api/pkg/inference-logger/liveness/handler.go
  api/pkg/transformer/server/grpc/server.go
  api/pkg/transformer/server/grpc/server_test.go
  api/pkg/transformer/server/rest/server_test.go
  api/queue/work/batch_deployment.go
  api/queue/work/batch_deployment_test.go
  api/service/prediction_job_service.go
  api/service/prediction_job_service_test.go
  api/service/testdata/model_endpoint_alert.yaml
  examples/custom-model/http_json/Dockerfile
  examples/custom-model/upi_v1/Dockerfile
  inference-logger.Dockerfile
  transformer.Dockerfile
Labels: maintenance

#570 bug: skip requirement comparison for pip reqs that is not a package
  python/sdk/merlin/requirements.py
  python/sdk/test/requirements/non_package_reqs_in.yaml
  python/sdk/test/requirements/non_package_reqs_out.yaml
  python/sdk/test/requirements_test.py
Labels: bug

#573 bugfix: avoid logging non-200 response and don't publish mesasge when there is error
  api/pkg/inference-logger/logger/mlobs_sink.go
  python/observation-publisher/publisher/prediction_log_consumer.py
Labels: bug

#574 Add Image Building API
  .github/workflows/merlin.yml
  api/api/response.go
  api/api/router.go
  api/api/version_image_api.go
  api/api/version_image_api_test.go
  api/cmd/api/main.go
  api/models/version_image.go
  api/pkg/imagebuilder/imagebuilder.go
  api/pkg/imagebuilder/mocks/image_builder.go
  api/service/mocks/version_image_service.go
  api/service/version_image_service.go
  api/service/version_image_service_test.go
Labels: enhancement

#572 chore: update documentation on model observability
  docs/user/templates/11_model_observability.md
Labels: documentation

#575 Image Building Clients & SDK
  .github/workflows/merlin.yml
  api/api/version_image_api_test.go
  api/client/api_version_image.go
  api/client/client.go
  api/client/model_build_image_options.go
  api/client/model_image_building_job_state.go
  api/client/model_image_building_job_status.go
  api/client/model_version_image.go
  api/models/version_image.go
  api/pkg/imagebuilder/imagebuilder.go
  api/pkg/imagebuilder/imagebuilder_test.go
  api/pkg/imagebuilder/mocks/image_builder.go
  api/queue/work/batch_deployment.go
  api/queue/work/batch_deployment_test.go
  api/queue/work/model_service_deployment.go
  api/queue/work/model_service_deployment_test.go
  api/service/prediction_job_service_test.go
  api/service/version_image_service.go
  api/service/version_image_service_test.go
  docs/user/generated/12_build_image.md
  docs/user/generated/model_deployment/01_deploying_a_model_version.md
  docs/user/templates/12_build_image.md
  docs/user/templates/model_deployment/01_deploying_a_model_version.md
  python/sdk/Makefile
  python/sdk/client/__init__.py
  python/sdk/client/api/__init__.py
  python/sdk/client/api/version_image_api.py
  python/sdk/client/models/__init__.py
  python/sdk/client/models/build_image_options.py
  python/sdk/client/models/image_building_job_state.py
  python/sdk/client/models/image_building_job_status.py
  python/sdk/client/models/version_image.py
  python/sdk/client_README.md
  python/sdk/merlin/__init__.py
  python/sdk/merlin/client.py
  python/sdk/merlin/fluent.py
  python/sdk/merlin/model.py
  python/sdk/merlin/version_image.py
  python/sdk/test/build_image_integration_test.py
  scripts/e2e/run-e2e.sh
  swagger.yaml
Labels: enhancement
