Repository caraml-dev/merlin, pull requests merged in 2024-09, with the labels that each got.

#603 fix: string validation in variable input schema
  ui/src/pages/version/components/forms/validation/schema.js
Labels: bug

#604 chore: add managed by label to namespace
  api/batch/resource_test.go
  api/cluster/controller_test.go
  api/cluster/labeller/labeller.go
  api/cluster/labeller/labeller_test.go
  api/cluster/namespace.go
  api/cluster/pdb_test.go
  api/cluster/resource/templater_gpu_test.go
  api/cluster/resource/templater_test.go
  api/cmd/api/main.go
  api/config/config.go
  api/config/config_test.go
  api/models/metadata.go
  api/models/metadata_test.go
  api/models/service_test.go
  api/pkg/imagebuilder/imagebuilder_test.go
  api/pkg/imagebuilder/janitor.go
  api/pkg/imagebuilder/janitor_test.go
  api/service/model_endpoint_service_test.go
Labels: enhancement

#608 fix(batch-predictor, pyfunc-server): Pin setuptools max version
  .github/workflows/release.yml
  python/batch-predictor/requirements.txt
  python/pyfunc-server/requirements.txt
Labels: bug

#609 fix(batch-predictor): Bump up pyarrow version limit
  python/batch-predictor/requirements.txt
Labels: bug, enhancement

#610 fix(cicd): Fix invalid pip installation commands
  .github/workflows/release.yml
Labels: bug
