Repository caraml-dev/merlin, pull requests merged in 2024-07, with the labels that each got.

#593 fix: Fix null pointer crash when deployment is not exist but secret exist …
  api/pkg/observability/deployment/deployment.go
  api/pkg/observability/deployment/deployment_test.go
Labels: bug

#594 fix(ui): Fix yup validation bugs
  ui/package.json
  ui/src/pages/version/components/forms/validation/schema.js
  ui/yarn.lock
Labels: bug

#596 fix(ui): Replace deprecated props in EuiDescriptionList
  ui/src/components/ContainerConfigTable.js
  ui/src/components/HorizontalDescriptionList.js
Labels: bug

#597 chore(batch-predictor,pyfunc-server): Bump up merlin-sdk versions in batch predictor and pyfunc server
  python/batch-predictor/requirements.txt
  python/pyfunc-server/requirements.txt
Labels: maintenance

#598 feat: Add more metrics and error log for observability publisher
  api/pkg/observability/deployment/deployment.go
  api/pkg/observability/deployment/deployment_test.go
  python/observation-publisher/publisher/__main__.py
  python/observation-publisher/publisher/metric.py
  python/observation-publisher/publisher/prediction_log_consumer.py
  python/observation-publisher/publisher/prediction_log_parser.py
Labels: enhancement
