Repository caraml-dev/merlin, pull requests merged in 2024-10, with the labels that each got.

#607 feat: Using secret to attach identity to pod for observability publisher
  api/config/observability.go
  api/pkg/observability/deployment/deployment.go
  api/pkg/observability/deployment/deployment_test.go
  api/pkg/observability/deployment/identity.go
  api/pkg/observability/deployment/identity_test.go
Labels: enhancement

#611 docs: add documentation for webhook
  docs/user/templates/webhook/01_webhook_config.md
Labels: documentation

#613 fix(cicd): Add google cloud sdk installation
  .github/workflows/merlin.yml
Labels: bug

#612 feat: add webhook call to other events
  api/api/model_endpoints_api.go
  api/api/models_api.go
  api/api/router.go
  api/api/versions_api.go
  api/api/versions_api_test.go
  api/cmd/api/main.go
  api/cmd/api/setup.go
  api/queue/work/model_service_deployment.go
  api/queue/work/model_service_deployment_test.go
  api/service/version_endpoint_service.go
  api/service/version_endpoint_service_test.go
  api/webhook/mocks/webhook.go
  api/webhook/request.go
  api/webhook/webhook.go
  api/webhook/webhook_test.go
  api/webhooks/webhooks.go
Labels: enhancement
