Repository caraml-dev/merlin, pull requests merged in 2024-02, with the labels that each got.

#530 Add troubleshooting deployment errors page
  docs/images/deployment_errors/crashloopbackoff.png
  docs/images/deployment_errors/image_building_oomkilled.png
  docs/images/deployment_errors/image_not_found.png
  docs/images/deployment_errors/version_log_history_tab.png
  docs/user/generated/01_getting_started.md
  docs/user/generated/03_deploying_a_model.md
  docs/user/generated/09_troubleshooting_deployment_errors.md
  docs/user/generated/examples/02_pyfunc_model.md
  docs/user/templates/09_troubleshooting_deployment_errors.md
  docs/user/templates/examples/02_pyfunc_model.md
Labels: documentation

#532 [sdk] Set experiment in model_version run
  examples/pyfunc/Pyfunc.ipynb
  examples/pyfunc/sklearn-model/model_2.joblib
  python/sdk/merlin/model.py
Labels: bug

#535 preload pyfunc v2 model to avoid pydantic schema generation error
  python/batch-predictor/main.py
  python/pyfunc-server/pyfuncserver/model/model.py
Labels: bug

#534 fix(cicd): Reduce memory footprint of e2e tests
  .github/workflows/merlin.yml
  python/sdk/test/conftest.py
  python/sdk/test/integration_test.py
  scripts/e2e/debug-e2e.sh
  scripts/e2e/run-e2e.sh
Labels: bug

#533 fix(api): Change default GPU Request value and prevent null values from being accepted
  api/cluster/resource/templater.go
  api/cluster/resource/templater_gpu_test.go
  ui/src/pages/version/components/forms/components/ResourcesPanel.js
Labels: bug

#528 Add documentation for model observability and model schema
  api/api/model_schema_api.go
  api/models/model_schema.go
  api/models/version.go
  api/service/model_schema_service.go
  api/storage/model_schema_storage.go
  docs/diagrams/model_observability.drawio.svg
  docs/user/generated/09_troubleshooting_deployment_errors.md
  docs/user/generated/10_model_schema.md
  docs/user/generated/11_model_observability.md
  docs/user/templates/10_model_schema.md
  docs/user/templates/11_model_observability.md
  docs/user/values.json
  python/sdk/merlin/autoscaling.py
  python/sdk/merlin/fluent.py
  python/sdk/merlin/logger.py
  python/sdk/merlin/merlin.py
  python/sdk/merlin/model.py
  python/sdk/merlin/model_schema.py
  python/sdk/merlin/observability/inference.py
  python/sdk/merlin/validation.py
  python/sdk/pyfunc.Dockerfile
Labels: documentation

#526 fix(image-builder): Refactor model image naming convention
  api/pkg/imagebuilder/imagebuilder_test.go
  api/pkg/imagebuilder/model_service_imagebuilder.go
  api/pkg/imagebuilder/prediction_job_imagebuilder.go
Labels: enhancement

#536 bug: fix json field typo for ranking output
  api/api/model_schema_api_test.go
  api/api/versions_api_test.go
  api/cluster/resource/templater_test.go
  api/models/model_schema.go
  api/service/model_schema_service_test.go
  api/storage/model_schema_storage_test.go
Labels: bug

#538 Add MLObs onboarding docs to gitbook
  docs/SUMMARY.md
  docs/user/generated/11_model_observability.md
Labels: documentation

#531 feat: reuse the same bigquery table for multiple model versions for Arize BQ Sink
  python/observation-publisher/Makefile
  python/observation-publisher/publisher/__main__.py
  python/observation-publisher/publisher/metric.py
  python/observation-publisher/publisher/observation_sink.py
  python/observation-publisher/publisher/prediction_log_consumer.py
  python/observation-publisher/publisher/prediction_log_parser.py
  python/observation-publisher/pyproject.toml
  python/observation-publisher/requirements-dev.txt
  python/observation-publisher/requirements.in
  python/observation-publisher/requirements.txt
  python/observation-publisher/tests/__init__.py
  python/observation-publisher/tests/common_fixtures.py
  python/observation-publisher/tests/test_config.py
  python/observation-publisher/tests/test_observation_sink.py
  python/observation-publisher/tests/test_prediction_log_consumer.py
Labels: enhancement

#542 fix: Fix order of pyfunc env vars based on priority
  api/cluster/resource/templater.go
  api/cluster/resource/templater_gpu_test.go
  api/cluster/resource/templater_test.go
Labels: bug
