Repository caraml-dev/merlin, pull requests merged in 2024-05, with the labels that each got.

#576 fix(api): Fix autoscaler target string parsing to not drop decimal numbers
  api/cluster/resource/templater_gpu_test.go
  api/cluster/resource/templater_test.go
  api/cluster/resource/utils.go
  python/sdk/test/conftest.py
Labels: bug

#577 chore: update Merlin doc
  docs/user/generated/11_model_observability.md
Labels: documentation

#579 Fix image building test for batch job
  python/sdk/test/build_image_integration_test.py
Labels: bug

#582 chore(batch-predictor,pyfunc-server): Bump merlin-sdk version in batch predictor and pyfunc server
  python/batch-predictor/requirements.txt
  python/pyfunc-server/requirements.txt
Labels: maintenance

#395 Fix custom model notebook examples
  examples/custom-model/upi_v1/custom-model-upi.ipynb
Labels: documentation

#580 fix(ui): Update min and step size of autoscaling target field
  ui/src/pages/version/components/forms/components/AutoscalingPolicyFormGroup.js
Labels: bug

#584 Fix PDB and VS not deleted
  api/cluster/controller.go
  api/cluster/pdb.go
  api/cluster/pdb_test.go
  api/cluster/virtual_service.go
Labels: bug

#585 chore: Update github actions and its dependencies
  .github/workflows/codesee-arch-diagram.yml
  .github/workflows/external.yml
  .github/workflows/merlin.yml
  .github/workflows/release.yml
  Makefile
Labels: maintenance

#581 Add pagination and partial name search to List Jobs APIs
  api/api/models_api_test.go
  api/api/prediction_job_api.go
  api/api/prediction_job_api_test.go
  api/api/router.go
  api/api/versions_api.go
  api/api/versions_api_test.go
  api/client/api_endpoint.go
  api/client/api_environment.go
  api/client/api_log.go
  api/client/api_model_endpoints.go
  api/client/api_model_schema.go
  api/client/api_models.go
  api/client/api_prediction_jobs.go
  api/client/api_project.go
  api/client/api_secret.go
  api/client/api_standard_transformer.go
  api/client/api_version.go
  api/client/api_version_image.go
  api/client/model_list_jobs_paginated_response.go
  api/client/model_paging.go
  api/go.mod
  api/go.sum
  api/service/mocks/prediction_job_service.go
  api/service/prediction_job_service.go
  api/service/prediction_job_service_test.go
  api/storage/mocks/prediction_job_storage.go
  api/storage/prediction_job_storage.go
  api/storage/prediction_job_storage_test.go
  python/sdk/client/__init__.py
  python/sdk/client/api/prediction_jobs_api.py
  python/sdk/client/models/__init__.py
  python/sdk/client/models/list_jobs_paginated_response.py
  python/sdk/client/models/paging.py
  python/sdk/client_README.md
  python/sdk/merlin/model.py
  python/sdk/test/model_test.py
  swagger.yaml
Labels: enhancement

#587 Add pagination to the List Jobs UI
  ui/src/config.js
  ui/src/job/JobListTable.js
  ui/src/job/Jobs.js
Labels: enhancement

#588 fix: Add resource request's max replica validation
  api/api/validator.go
  api/api/version_endpoints_api.go
  api/api/version_endpoints_api_test.go
  python/sdk/merlin/model.py
  python/sdk/merlin/resource_request.py
  python/sdk/test/resource_request_test.py
Labels: bug

#589 cherry-pick: Add resource request's max replica validation (#588) for hotfix
  api/api/validator.go
  api/api/version_endpoints_api.go
  api/api/version_endpoints_api_test.go
  python/sdk/merlin/model.py
  python/sdk/merlin/resource_request.py
  python/sdk/test/resource_request_test.py
Labels: bug

#590 fix: Only use columns that already defined in inference schema
  python/observation-publisher/publisher/prediction_log_consumer.py
  python/observation-publisher/publisher/prediction_log_parser.py
  python/observation-publisher/tests/test_prediction_log_consumer.py
Labels: bug
