Repository caraml-dev/merlin, pull requests merged in 2024-03, with the labels that each got.

#539 feat(api): Expose tolerations and node selectors for batch jobs
  .github/workflows/merlin.yml
  api/batch/controller.go
  api/batch/controller_test.go
  api/batch/resource.go
  api/batch/resource_test.go
  api/cmd/api/setup.go
  api/config/batch.go
  api/config/config.go
  config.yaml
  scripts/e2e/run-e2e.sh
  scripts/e2e/values-e2e.yaml
Labels: enhancement

#545 Revert "fix(image-builder): Refactor model image naming convention (#526)
  api/pkg/imagebuilder/imagebuilder_test.go
  api/pkg/imagebuilder/model_service_imagebuilder.go
  api/pkg/imagebuilder/prediction_job_imagebuilder.go
Labels: maintenance

#543 Refactor inference schema
  api/api/model_schema_api_test.go
  api/api/versions_api_test.go
  api/client/model_binary_classification_output.go
  api/client/model_model_prediction_output.go
  api/client/model_ranking_output.go
  api/client/model_regression_output.go
  api/client/model_schema_spec.go
  api/cluster/resource/templater_test.go
  api/models/model_schema.go
  api/service/model_schema_service_test.go
  api/storage/model_schema_storage_test.go
  docs/user/templates/11_model_observability.md
  python/observation-publisher/conf/environment/example-override.yaml
  python/observation-publisher/publisher/observation_sink.py
  python/observation-publisher/publisher/prediction_log_consumer.py
  python/observation-publisher/publisher/prediction_log_parser.py
  python/observation-publisher/tests/test_config.py
  python/observation-publisher/tests/test_observation_sink.py
  python/observation-publisher/tests/test_prediction_log_consumer.py
  python/sdk/client/models/binary_classification_output.py
  python/sdk/client/models/ranking_output.py
  python/sdk/client/models/regression_output.py
  python/sdk/client/models/schema_spec.py
  python/sdk/client_README.md
  python/sdk/merlin/model_schema.py
  python/sdk/merlin/observability/inference.py
  python/sdk/test/integration_test.py
  python/sdk/test/model_schema_test.py
  python/sdk/test/model_test.py
  python/sdk/test/observability_test.py
  swagger.yaml
Labels: enhancement

#544 feat: Support HTTP predictor for UPI
  api/cluster/resource/templater.go
  api/cluster/resource/templater_test.go
  api/models/service.go
  api/models/service_test.go
  api/pkg/transformer/constant.go
  api/pkg/transformer/server/config/options.go
  api/pkg/transformer/server/grpc/predictor.go
  api/pkg/transformer/server/grpc/server.go
  api/pkg/transformer/server/grpc/server_test.go
  api/pkg/transformer/server/rest/server.go
  python/sdk/test/pyfunc_upi_integration_test.py
Labels: enhancement

#546 feat(api,ui): Add new max allowed replicas field to env configs and relevant checks
  api/cluster/controller.go
  api/cluster/controller_test.go
  api/cluster/errors.go
  api/cmd/api/setup.go
  api/config/config.go
  api/config/deployment.go
  api/config/environment.go
  api/models/environment.go
  db-migrations/37_environments_add_max_allowed_replicas.down.sql
  db-migrations/37_environments_add_max_allowed_replicas.up.sql
  scripts/e2e/values-e2e.yaml
  ui/src/config.js
  ui/src/pages/version/DeploymentPanelHeader.js
  ui/src/pages/version/components/forms/DeployModelVersionForm.js
  ui/src/pages/version/components/forms/components/DeploymentConfigPanel.js
  ui/src/pages/version/components/forms/components/ResourcesPanel.js
  ui/src/pages/version/components/forms/components/SelectTransformerPanel.js
  ui/src/pages/version/components/forms/steps/ModelStep.js
  ui/src/pages/version/components/forms/steps/TransformerStep.js
  ui/src/pages/version/components/forms/validation/schema.js
Labels: enhancement

#548 fix: Fix UPI integration test
  python/sdk/test/pyfunc_upi_integration_test.py
Labels: bug

#549 fix(ui): Fix negative values shown on the replicas slider when an env is selected during model deployment
  ui/src/pages/version/components/forms/DeployModelVersionForm.js
  ui/src/pages/version/components/forms/components/ResourcesPanel.js
Labels: bug

#550 feat: Add observability publisher deployment
  api/cmd/api/main.go
  api/cmd/api/setup.go
  api/config/config.go
  api/config/observability.go
  api/models/model.go
  api/models/model_endpoint.go
  api/models/model_schema.go
  api/models/observability_publisher.go
  api/models/service.go
  api/pkg/observability/deployment/config.go
  api/pkg/observability/deployment/deployment.go
  api/pkg/observability/deployment/deployment_test.go
  api/pkg/observability/deployment/mocks/deployer.go
  api/pkg/observability/deployment/util.go
  api/pkg/observability/event/event.go
  api/pkg/observability/event/event_test.go
  api/pkg/observability/event/mocks/event_producer.go
  api/queue/work/model_service_deployment.go
  api/queue/work/model_service_deployment_test.go
  api/queue/work/observability_publisher_deployment.go
  api/queue/work/observability_publisher_deployment_test.go
  api/service/model_endpoint_service.go
  api/service/model_endpoint_service_test.go
  api/service/version_endpoint_service.go
  api/storage/mocks/observability_publisher_storage.go
  api/storage/mocks/version_storage.go
  api/storage/observability_publisher_storage.go
  api/storage/observability_publisher_storage_test.go
  api/storage/version_storage.go
  api/storage/version_storage_test.go
  db-migrations/38_supported_observability_on_models.down.sql
  db-migrations/38_supported_observability_on_models.up.sql
  db-migrations/39_observability_publisher.down.sql
  db-migrations/39_observability_publisher.up.sql
  python/sdk/test/pyfunc_integration_test.py
  scripts/e2e/values-e2e.yaml
Labels: enhancement

#552 Ingest rank score to Arize
  python/observation-publisher/publisher/observation_sink.py
Labels: bug

#553 fix(image-builder): use google keychain for Artifact Registry domains
  api/pkg/imagebuilder/imagebuilder.go
Labels: bug

#555 fix(image-building): Update process_conda_env.sh
  python/batch-predictor/docker/process_conda_env.sh
  python/pyfunc-server/docker/process_conda_env.sh
  ui/src/pages/version/components/forms/steps/TransformerStep.js
Labels: bug, enhancement

#557 Bump dependencies for batch-predictor and pyfunc-server
  python/batch-predictor/requirements.txt
  python/pyfunc-server/requirements.txt
Labels: bug, enhancement

#556 Create topic before publishing prediction log
  api/cluster/resource/templater.go
  api/cluster/resource/templater_test.go
  api/config/config.go
  python/pyfunc-server/pyfuncserver/config.py
  python/pyfunc-server/pyfuncserver/publisher/kafka.py
Labels: bug

#554 Add support for mlobs sink on logger
  api/cmd/inference-logger/main.go
  api/cmd/inference-logger/main_test.go
  api/go.mod
  api/go.sum
  api/pkg/inference-logger/logger/handler_test.go
  api/pkg/inference-logger/logger/kafka_sink.go
  api/pkg/inference-logger/logger/kafka_sink_test.go
  api/pkg/inference-logger/logger/mlobs_sink.go
  api/pkg/inference-logger/logger/mlobs_sink_test.go
  api/pkg/inference-logger/logger/types.go
  api/pkg/inference-logger/mocks/KafkaAdmin.go
Labels: enhancement

#558 Loosen merlin-sdk deps in components
  python/batch-predictor/requirements.txt
  python/pyfunc-server/requirements.txt
  python/pyfunc-server/test/test_examples.py
  python/sdk/merlin/docker/pyfunc.Dockerfile
  python/sdk/merlin/pyfunc.py
Labels: enhancement

#559 feat: add mlobs logger url config
  api/cmd/api/setup.go
  api/config/config.go
  api/pkg/inference-logger/logger/types.go
  api/queue/work/model_service_deployment.go
  api/service/version_endpoint_service.go
Labels: enhancement

#561 handle malformed log entry for mlobs sink
  api/pkg/inference-logger/logger/mlobs_sink.go
  api/pkg/inference-logger/logger/mlobs_sink_test.go
Labels: bug
