Repository caraml-dev/merlin, pull requests merged in 2024-01, with the labels that each got.

#509 feat: update observation publisher to use newer sdk
  .github/workflows/merlin.yml
  .github/workflows/release.yml
  python/Makefile
  python/observation-publisher/Dockerfile
  python/observation-publisher/Makefile
  python/observation-publisher/README.md
  python/observation-publisher/conf/environment/example-override.yaml
  python/observation-publisher/publisher/__main__.py
  python/observation-publisher/publisher/config.py
  python/observation-publisher/publisher/observability_backend.py
  python/observation-publisher/publisher/prediction_log_consumer.py
  python/observation-publisher/publisher/prediction_log_parser.py
  python/observation-publisher/requirements-dev.txt
  python/observation-publisher/requirements.in
  python/observation-publisher/requirements.txt
  python/observation-publisher/tests/test_config.py
  python/observation-publisher/tests/test_observability_backend.py
  python/observation-publisher/tests/test_prediction_log_consumer.py
Labels: enhancement

#502 feat: Support model observability to pyfunc model
  api/api/validator.go
  api/api/version_endpoints_api_test.go
  api/cluster/resource/templater.go
  api/cluster/resource/templater_test.go
  python/pyfunc-server/pyfuncserver/protocol/rest/handler.py
  python/pyfunc-server/pyfuncserver/protocol/upi/server.py
  python/pyfunc-server/test/test_http.py
  python/sdk/merlin/pyfunc.py
  python/sdk/test/pyfunc_test.py
Labels: enhancement

#520 Adding back SUMMARY.md file
  docs/SUMMARY.md
  docs/user/generated/03_deploying_a_model.md
Labels: documentation

#521 fix: move git initialization to function body
  python/sdk/merlin/pyfunc.py
Labels: bug

#523 fix: make sure transformer property on version endpoint is not undefined
  python/sdk/merlin/endpoint.py
Labels: bug

#522 fix: Incorrect request body for create and patch version
  api/api/model_schema_api.go
  api/api/model_schema_api_test.go
  api/api/versions_api.go
  api/api/versions_api_test.go
  api/models/model_schema.go
  api/models/version.go
  openapi-api-codegen.yaml
  openapi-sdk-codegen.yaml
  python/sdk/client/models/binary_classification_output.py
  python/sdk/client/models/model_prediction_output.py
  python/sdk/client/models/ranking_output.py
  python/sdk/client/models/regression_output.py
  python/sdk/merlin/model.py
  python/sdk/merlin/model_schema.py
  python/sdk/test/integration_test.py
  python/sdk/test/model_schema_test.py
  python/sdk/test/model_test.py
  swagger.yaml
Labels: bug

#525 fix: Reduce memory usage when publishing prediction log to kafka
  python/pyfunc-server/pyfuncserver/publisher/kafka.py
Labels: bug

#517 fix(api): Fix failing recovery of deployment attempts interrupted by API server pod termination
  api/cluster/controller.go
  api/cluster/controller_test.go
  api/queue/work/model_service_deployment.go
  api/queue/work/model_service_deployment_test.go
  api/storage/deployment_storage.go
  api/storage/deployment_storage_test.go
  api/storage/mocks/deployment_storage.go
Labels: bug

#527 fix: Retraining model for PyFunc E2E test
  python/sdk/test/pyfunc_integration_test.py
Labels: bug

#519 feat(api): Introduce CPU and memory limit request factors to API server
  api/cluster/controller_test.go
  api/cluster/resource/templater.go
  api/cluster/resource/templater_gpu_test.go
  api/cluster/resource/templater_test.go
  api/cluster/resource/utils.go
  api/config/config.go
  api/config/deployment.go
  api/config/environment.go
Labels: enhancement

#524 Propagate image building and model deployment errors
  api/cluster/controller.go
  api/cluster/controller_test.go
  api/cluster/errors.go
  api/go.mod
  api/go.sum
  api/pkg/imagebuilder/imagebuilder.go
  api/pkg/imagebuilder/imagebuilder_test.go
  api/utils/kubernetes.go
  api/utils/kubernetes_test.go
  api/utils/table.go
  api/utils/table_test.go
  ui/src/pages/version/HistoryDetails.js
Labels: enhancement
