Repository caraml-dev/merlin, pull requests merged in 2025-05, with the labels that each got.

#644 fix(ui): add maxcompute support to job detail page
  ui/src/pages/job/components/SinkConfig.js
  ui/src/pages/job/components/SourceConfig.js
  ui/src/services/job/Job.js
Labels: bug

#643 feat(ui): update templating of monitoring url
  ui/package.json
  ui/src/pages/job/JobPage.js
  ui/src/pages/job/components/JobActions.js
  ui/src/pages/job/components/JobDetailTabNavigation.js
  ui/src/pages/job/components/JobRunPanel.js
  ui/src/pages/job/components/JobsTable.js
  ui/src/pages/job/utils/monitoringUrl.js
  ui/yarn.lock
Labels: enhancement, breaking

#647 fix(ui): revert changes in Job constructor
  ui/src/pages/job/components/JobRunPanel.js
  ui/src/services/job/Job.js
Labels: bug

#648 feat(api): Add alert path prefix as configuration field
  api/cmd/api/main.go
  api/config/config.go
  api/config/config_test.go
  api/config/testdata/base-configs-1.yaml
  api/service/model_endpoint_alert_service.go
Labels: enhancement

#645 Set init statement and autoSelectLimit for maxcompute source
  python/batch-predictor/merlinpyspark/source.py
Labels: bug, enhancement

#646 [merlin] use eui super select to list registries
  ui/package.json
Labels: bug

#649 chore(sdk): Bump up pyfunc package versions
  .github/workflows/merlin.yml
  .github/workflows/release.yml
  .readthedocs.yml
  Makefile
  api/api/versions_api.go
  api/config/config.go
  api/config/config_test.go
  api/config/testdata/base-configs-1.yaml
  api/pkg/imagebuilder/imagebuilder_test.go
  docs/developer/e2e-test.md
  examples/metrics/env.yaml
  examples/pyfunc-upi/env.yaml
  examples/pyfunc/env.yaml
  examples/transformer/custom-transformer/env.yaml
  examples/transformer/feast-enricher-transformer/env.yaml
  examples/transformer/standard-transformer/env.yaml
  examples/transformer/upi/env.yaml
  python/batch-predictor/README.md
  python/batch-predictor/setup.py
  python/batch-predictor/test-model/MLmodel
  python/batch-predictor/test-model/conda.yaml
  python/batch-predictor/test-model/python_env.yaml
  python/observation-publisher/requirements.txt
  python/pyfunc-scaffolding/{{cookiecutter.model_slug}}/Pipfile
  python/pyfunc-scaffolding/{{cookiecutter.model_slug}}/env/conda.yaml
  python/pyfunc-server/pyfuncserver/utils/contants.py
  python/pyfunc-server/setup.py
  python/pyfunc-server/test/local-artifacts/MLmodel
  python/pyfunc-server/test/local-artifacts/conda.yaml
  python/pyfunc-server/test/local-artifacts/python_env.yaml
  python/sdk/Dockerfile
  python/sdk/merlin/model.py
  python/sdk/requirements.txt
Labels: maintenance
